### ISSUE TITLE
Add to stackage-lts

### ISSUE THREAD

**Issue by olynch** [diagrams/dual-tree#11]
I have built this successfully on the lts-11.11 stack resolver, so there seems to be no reason why it isn't included in the latest slack lts. Could you please add it back in?

**Comment by byorgey** [comment]
Well, it didn't build at the time LTS-11 was first released (a bunch of diagrams-related packages are excluded from LTS-11), and in general packages aren't re-added to a particular LTS series unless it is explicitly requested to add them.  Is there a particular reason you need this added to LTS-11 (as opposed to just using LTS-10 or specifying it as an extra-dep)?  Honestly I'd rather spend my time on other things (like working on diagrams 2.0) rather than going back through and making pull requests to add a bunch of packages to LTS-11.

**Comment by olynch** [comment]
OK, that's fine, we can just wait for lts-12 and use nightly in the meantime. Thank you (and I'm excited for diagrams 2.0!)
